# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/Account.ui'
#
# Created: Mon Jan 27 17:06:16 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Account(object):
    def setupUi(self, Account):
        Account.setObjectName("Account")
        Account.resize(400, 400)
        Account.setMinimumSize(QtCore.QSize(400, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/toolbar/account-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Account.setWindowIcon(icon)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Account)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableView = QtGui.QTableView(Account)
        self.tableView.setObjectName("tableView")
        self.horizontalLayout_2.addWidget(self.tableView)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButtonAdd = QtGui.QPushButton(Account)
        self.pushButtonAdd.setMinimumSize(QtCore.QSize(0, 24))
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.verticalLayout.addWidget(self.pushButtonAdd)
        self.pushButtonEdit = QtGui.QPushButton(Account)
        self.pushButtonEdit.setMinimumSize(QtCore.QSize(0, 24))
        self.pushButtonEdit.setObjectName("pushButtonEdit")
        self.verticalLayout.addWidget(self.pushButtonEdit)
        self.pushButtonDelete = QtGui.QPushButton(Account)
        self.pushButtonDelete.setMinimumSize(QtCore.QSize(0, 24))
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.verticalLayout.addWidget(self.pushButtonDelete)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtGui.QLabel(Account)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(70, 0))
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEdit0acc_username = QtGui.QLineEdit(Account)
        self.lineEdit0acc_username.setEnabled(False)
        self.lineEdit0acc_username.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit0acc_username.setFont(font)
        self.lineEdit0acc_username.setObjectName("lineEdit0acc_username")
        self.horizontalLayout_3.addWidget(self.lineEdit0acc_username)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtGui.QLabel(Account)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(70, 0))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.lineEdit0acc_password = QtGui.QLineEdit(Account)
        self.lineEdit0acc_password.setEnabled(False)
        self.lineEdit0acc_password.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit0acc_password.setFont(font)
        self.lineEdit0acc_password.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEdit0acc_password.setObjectName("lineEdit0acc_password")
        self.horizontalLayout_4.addWidget(self.lineEdit0acc_password)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtGui.QLabel(Account)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(70, 0))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.comboBox0acc_roles_level = QtGui.QComboBox(Account)
        self.comboBox0acc_roles_level.setEnabled(False)
        self.comboBox0acc_roles_level.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.comboBox0acc_roles_level.setFont(font)
        self.comboBox0acc_roles_level.setObjectName("comboBox0acc_roles_level")
        self.comboBox0acc_roles_level.addItem("")
        self.comboBox0acc_roles_level.addItem("")
        self.comboBox0acc_roles_level.addItem("")
        self.comboBox0acc_roles_level.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox0acc_roles_level)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.pushButtonCancel = QtGui.QPushButton(Account)
        self.pushButtonCancel.setEnabled(False)
        self.pushButtonCancel.setMinimumSize(QtCore.QSize(0, 24))
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout_6.addWidget(self.pushButtonCancel)
        self.pushButtonSave = QtGui.QPushButton(Account)
        self.pushButtonSave.setEnabled(False)
        self.pushButtonSave.setMinimumSize(QtCore.QSize(0, 24))
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.horizontalLayout_6.addWidget(self.pushButtonSave)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.label.setBuddy(self.lineEdit0acc_username)
        self.label_2.setBuddy(self.lineEdit0acc_password)
        self.label_3.setBuddy(self.comboBox0acc_roles_level)

        self.retranslateUi(Account)
        QtCore.QMetaObject.connectSlotsByName(Account)
        Account.setTabOrder(self.pushButtonAdd, self.pushButtonEdit)
        Account.setTabOrder(self.pushButtonEdit, self.pushButtonDelete)
        Account.setTabOrder(self.pushButtonDelete, self.lineEdit0acc_username)
        Account.setTabOrder(self.lineEdit0acc_username, self.lineEdit0acc_password)
        Account.setTabOrder(self.lineEdit0acc_password, self.comboBox0acc_roles_level)
        Account.setTabOrder(self.comboBox0acc_roles_level, self.pushButtonSave)
        Account.setTabOrder(self.pushButtonSave, self.pushButtonCancel)
        Account.setTabOrder(self.pushButtonCancel, self.tableView)

    def retranslateUi(self, Account):
        Account.setWindowTitle(QtGui.QApplication.translate("Account", "User Account", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAdd.setText(QtGui.QApplication.translate("Account", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonEdit.setText(QtGui.QApplication.translate("Account", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonDelete.setText(QtGui.QApplication.translate("Account", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Account", "&Username", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Account", "&Password", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Account", "&Roles Level", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox0acc_roles_level.setItemText(0, QtGui.QApplication.translate("Account", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox0acc_roles_level.setItemText(1, QtGui.QApplication.translate("Account", "400", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox0acc_roles_level.setItemText(2, QtGui.QApplication.translate("Account", "800", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox0acc_roles_level.setItemText(3, QtGui.QApplication.translate("Account", "999", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCancel.setText(QtGui.QApplication.translate("Account", "&Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSave.setText(QtGui.QApplication.translate("Account", "&Save", None, QtGui.QApplication.UnicodeUTF8))

import res_rc
