# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConfirmationTable.ui'
#
# Created: Sat Jan 04 16:14:57 2014
#      by: pyside-uic 0.2.15 running on PySide 1.2.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ConfirmationTable(object):
    def setupUi(self, ConfirmationTable):
        ConfirmationTable.setObjectName("ConfirmationTable")
        ConfirmationTable.setWindowModality(QtCore.Qt.ApplicationModal)
        ConfirmationTable.resize(640, 400)
        ConfirmationTable.setMinimumSize(QtCore.QSize(640, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/mainwindow-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ConfirmationTable.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(ConfirmationTable)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LblProcess = QtGui.QLabel(ConfirmationTable)
        self.LblProcess.setObjectName("LblProcess")
        self.horizontalLayout_2.addWidget(self.LblProcess)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tableViewProcess = QtGui.QTableView(ConfirmationTable)
        self.tableViewProcess.setObjectName("tableViewProcess")
        self.verticalLayout.addWidget(self.tableViewProcess)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LblTotalProcess = QtGui.QLabel(ConfirmationTable)
        self.LblTotalProcess.setObjectName("LblTotalProcess")
        self.horizontalLayout.addWidget(self.LblTotalProcess)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.BtnCancel = QtGui.QPushButton(ConfirmationTable)
        self.BtnCancel.setObjectName("BtnCancel")
        self.horizontalLayout.addWidget(self.BtnCancel)
        self.BtnEditAboveRec = QtGui.QPushButton(ConfirmationTable)
        self.BtnEditAboveRec.setMinimumSize(QtCore.QSize(120, 0))
        self.BtnEditAboveRec.setObjectName("BtnEditAboveRec")
        self.horizontalLayout.addWidget(self.BtnEditAboveRec)
        self.BtnProcess = QtGui.QPushButton(ConfirmationTable)
        self.BtnProcess.setObjectName("BtnProcess")
        self.horizontalLayout.addWidget(self.BtnProcess)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.LblSuccess = QtGui.QLabel(ConfirmationTable)
        self.LblSuccess.setObjectName("LblSuccess")
        self.horizontalLayout_3.addWidget(self.LblSuccess)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.tableViewSuccess = QtGui.QTableView(ConfirmationTable)
        self.tableViewSuccess.setObjectName("tableViewSuccess")
        self.verticalLayout.addWidget(self.tableViewSuccess)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.LblTotalSuccess = QtGui.QLabel(ConfirmationTable)
        self.LblTotalSuccess.setObjectName("LblTotalSuccess")
        self.horizontalLayout_4.addWidget(self.LblTotalSuccess)
        self.line = QtGui.QFrame(ConfirmationTable)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_4.addWidget(self.line)
        self.LblReport = QtGui.QLabel(ConfirmationTable)
        self.LblReport.setOpenExternalLinks(True)
        self.LblReport.setObjectName("LblReport")
        self.horizontalLayout_4.addWidget(self.LblReport)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.BtnReport = QtGui.QPushButton(ConfirmationTable)
        self.BtnReport.setObjectName("BtnReport")
        self.horizontalLayout_4.addWidget(self.BtnReport)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.progressBar = QtGui.QProgressBar(ConfirmationTable)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)

        self.retranslateUi(ConfirmationTable)
        QtCore.QMetaObject.connectSlotsByName(ConfirmationTable)

    def retranslateUi(self, ConfirmationTable):
        ConfirmationTable.setWindowTitle(QtGui.QApplication.translate("ConfirmationTable", "Confirmation Table", None, QtGui.QApplication.UnicodeUTF8))
        self.LblProcess.setText(QtGui.QApplication.translate("ConfirmationTable", "Record(s) to be processed:", None, QtGui.QApplication.UnicodeUTF8))
        self.LblTotalProcess.setText(QtGui.QApplication.translate("ConfirmationTable", "Total: 0 record(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.BtnCancel.setText(QtGui.QApplication.translate("ConfirmationTable", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.BtnEditAboveRec.setText(QtGui.QApplication.translate("ConfirmationTable", "Edit Above Record(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.BtnProcess.setText(QtGui.QApplication.translate("ConfirmationTable", "Process", None, QtGui.QApplication.UnicodeUTF8))
        self.LblSuccess.setText(QtGui.QApplication.translate("ConfirmationTable", "Successful processed record(s):", None, QtGui.QApplication.UnicodeUTF8))
        self.LblTotalSuccess.setText(QtGui.QApplication.translate("ConfirmationTable", "Success: 0 record(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.LblReport.setText(QtGui.QApplication.translate("ConfirmationTable", "Report is going to be generated right after the process is finished", None, QtGui.QApplication.UnicodeUTF8))
        self.BtnReport.setText(QtGui.QApplication.translate("ConfirmationTable", "Report", None, QtGui.QApplication.UnicodeUTF8))

